baseurl = "http://blog.algolab.jp/"
theme = "angels-ladder"
languageCode = "ja"
title = "ALGO GEEKS"
disqusShortname = "algolab"

[Params]
subtitle = "人工知能・ロボットを中心とした情報を発信"
showsRSS = true
copyright = "© 2016 Algo Lab Inc."
analytics = "UA-70610940-1"
shareThis = "68ab120e-79d6-4b3c-ae2e-4e7f8099de14"

[Temp]
speaklyn = "21fa1a94982b9c244e977065006f3d80"
