baseurl = "http://blog.algolab.jp/"
theme = "angels-ladder"
languageCode = "ja"
title = "blog.alogolab.jp"
disqusShortname = "algolab"

[Params]
subtitle = "人工知能・ロボットについて"
showsRSS = true
copyright = "© 2016 Algo Lab Inc."
analytics = "UA-70610940-1"
shareThis = "68ab120e-79d6-4b3c-ae2e-4e7f8099de14"
