baseurl = "http://blog.algolab.jp/"
disqusShortname = "algolab"
hasCJKLanguage = true
languageCode = "ja"
theme = "angels-ladder"
title = "ALGO GEEKS"

[Params]
analytics = "UA-70610940-1"
copyright = "© 2016 Algo Lab Inc."
facebookApp = "131078513971096"
loyalTracker = "073b51e13b38"
subtitle = "株式会社アルゴラボBLOG"
showsRSS = true
shareThis = "68ab120e-79d6-4b3c-ae2e-4e7f8099de14"

[taxonomies]
author = "authors"
tag = "tags"

[Temp]
speaklyn = "21fa1a94982b9c244e977065006f3d80"
